name: Build Site
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Site
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'

      - run: ./scripts/fetch-good-read.rb
      - run: cd website && bundle install && bundle exec jekyll build && cd ..
      - run: ./scripts/push-to-gh-pages.sh ${{ secrets.commit_secret }}
